# Generated by Django 2.2.7 on 2019-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=32)),
                ('course', models.CharField(max_length=20)),
                ('shift', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('contact_no', models.CharField(max_length=14)),
            ],
        ),
    ]
